# Generated by Django 3.2.3 on 2021-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AlterModelOptions(
            name='testdata',
            options={'verbose_name_plural': 'Test Data'},
        ),
    ]
