# Generated by Django 3.2.3 on 2021-06-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0004_alter_testdata_random_encryptionnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='random_encryptionNum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
