# Generated by Django 3.2.3 on 2021-06-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0005_alter_testdata_random_encryptionnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='random_encryptionNum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
