# Generated by Django 3.2.3 on 2021-06-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0006_alter_testdata_random_encryptionnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskName',
        ),
    ]
